### ISSUE TITLE
Libreelec 9 vfs.rar 2.6.0 crashes when navigate to movies

### ISSUE THREAD

**Issue by od3m** [xbmc/vfs.rar#37]
Hey all

Kodi within Libreelec 9.0.1 crashes everytime when navigating to movies with enabled vfs.rar addon in version 2.5.2 or 2.6.0.
With disabled addon everything works fine. 
Nothing to be found in the logs. 

Hope you guys have any ideas !

best
Mario

**Comment by DaVukovic** [comment]
Could you please share the logs. I have the same add-on installed (compiled from source and btw. it's 2.0.6 and not 2.6.0 ;) ) and I can't reprduce your issue using Ubuntu.

Steps to reproduce:

- install that addon
- enable that add-on
- navigate to my movie library

works fine for me. So please enable debug logging, reproduce your issue and provide the log. Otherwise it's hard to help and it could also be something LibreELEC specific. But the log will tell

**Comment by od3m** [comment]
Hi DaVukovic 

Thanks For your Investigation. Meanwhile i pointed out that it was some currupted rars that results in this problem. 
I removed them and everything works fine again. 
For some reason, with LE8 that seemed not to be a problem at all. 

Thanks again !
